server:
  # 服务端口
  port: 6000
  servlet:
    # 项目contextPath
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://**********/wechat?serverTimezone=Asia/Shanghai
    username: *****
    password: ************
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-Locations: classpath:mapping/*.xml
