server:
  # 服务端口
  port: 6000
  servlet:
    # 项目contextPath
    context-path: /
mybatis:
  mapper-Locations: classpath:mapping/*.xml
spring:
  datasource:
    url: jdbc:mysql://47.92.211.200:10024/wechat?serverTimezone=UTC
    username: csnight
    password: night@123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
